### ISSUE TITLE
wpfui.lepo.co Website returns 404 for documentation and tutorials

### ISSUE THREAD

**Issue by Paliverse** [lepoco/wpfui#407]
### Describe the bug

Unable to access the docs and tutorials due to 404 error

### To Reproduce

Visit the docs on the webiste https://wpfui.lepo.co/documentation/

### Expected behavior

to view the docs

### OS version

N/A

### .NET version

N/A

### WPF-UI NuGet version

N/A

**Comment by sharanoth** [comment]
This is resolved.

**Comment by Paliverse** [comment]
Awesome! Thanks for this great UI.

**Comment by alxkalinin** [comment]
> Awesome! Thanks for this great UI.

Did you able to see the docs? On my computer, I still have a 404 error.

**Comment by bry-decelles** [comment]
404 Errors are back.

**Comment by alxkalinin** [comment]
Could we reopen the issue?

**Comment by Paliverse** [comment]
I’m not seeing any 404’s but I’ll open If people still experience it

**Comment by bry-decelles** [comment]
It looks like it's WINDOWS.md that is returning the 404 error
![image](https://user-images.githubusercontent.com/68069134/194107044-52fe207a-fc4c-493d-9de3-d422d076942a.png)
